language: node_js
node_js:
  - v12
  - v10
cache:
  directories:
    - "node_modules"

env:
  - TWITTER_USERNAME=username
  - TWITTER_API_KEY=here-the-value
  - TWITTER_API_SECRET=here-the-value
  - TWITTER_ACCESS_TOKEN=here-the-value
  - TWITTER_ACCESS_TOKEN_SECRET=here-the-value
  - DAYS_TO_DUST=3

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run test:coverage
